
cd /home/mjackson/projects/simple-widgets

mv src/AppCore.js src/AppCore.jsx
mv src/ChoiceTextSearchable.js src/ChoiceTextSearchable.jsx
mv src/AlertModal.js src/AlertModal.jsx
mv src/ConfirmModal.js src/ConfirmModal.jsx
mv src/CheckBoxGroup.js src/CheckBoxGroup.jsx
mv src/Choice.js src/Choice.jsx
mv src/CheckBox.js src/CheckBox.jsx
mv src/ContextMenu.js src/ContextMenu.jsx
mv src/DateInput.js src/DateInput.jsx
mv src/HeaderModal.js src/HeaderModal.jsx
mv src/ChoiceText.js src/ChoiceText.jsx
mv src/Header.js src/Header.jsx
mv src/ErrorModal.js src/ErrorModal.jsx
mv src/Home.js src/Home.jsx
mv src/List.js src/List.jsx
mv src/InputFile.js src/InputFile.jsx
mv src/Link.js src/Link.jsx
mv src/Invalid.js src/Invalid.jsx
mv src/OpenTab.js src/OpenTab.jsx
mv src/NavigateBar.js src/NavigateBar.jsx
mv src/MenuBar.js src/MenuBar.jsx
mv src/Modal.js src/Modal.jsx
mv src/ProgressCircles.js src/ProgressCircles.jsx
mv src/PageTitle.js src/PageTitle.jsx
mv src/Redirect.js src/Redirect.jsx
mv src/SimpleTable.js src/SimpleTable.jsx
mv src/Outline.js src/Outline.jsx
mv src/Radio.js src/Radio.jsx
mv src/Slider.js src/Slider.jsx
mv src/StatusBox.js src/StatusBox.jsx
mv src/UserSection.js src/UserSection.jsx
mv src/SpreadSheet.js src/SpreadSheet.jsx
mv src/DoubleListBox.js src/DoubleListBox.jsx
mv src/forms/Button.js src/forms/Button.jsx
mv src/SearchSortTable.js src/SearchSortTable.jsx
mv src/forms/ControlledInput.js src/forms/ControlledInput.jsx
mv src/forms/DatabaseLoadingIcon.js src/forms/DatabaseLoadingIcon.jsx
mv src/forms/ControlledTextarea.js src/forms/ControlledTextarea.jsx
mv src/forms/ErrorList.js src/forms/ErrorList.jsx
mv src/forms/Form.js src/forms/Form.jsx
mv src/forms/FormFields.js src/forms/FormFields.jsx
mv src/forms/EntryScreen.js src/forms/EntryScreen.jsx
mv src/forms/FieldGenerator.js src/forms/FieldGenerator.jsx
mv src/forms/FormChoice.js src/forms/FormChoice.jsx
mv src/forms/Gears.js src/forms/Gears.jsx
mv src/forms/MakeModal.js src/forms/MakeModal.jsx
mv src/forms/FormHeader.js src/forms/FormHeader.jsx
mv src/forms/NarrowForm.js src/forms/NarrowForm.jsx
mv src/forms/FormTable.js src/forms/FormTable.jsx
mv src/forms/Input.js src/forms/Input.jsx
mv src/forms/SimpleDataTable.js src/forms/SimpleDataTable.jsx
mv src/forms/Show.js src/forms/Show.jsx
mv src/forms/genRowBuilder.js src/forms/genRowBuilder.jsx
mv src/forms/SimpleEntryScreen.js src/forms/SimpleEntryScreen.jsx
mv src/forms/img/FormImages.js src/forms/img/FormImages.jsx

